### ISSUE TITLE
Impossible d'utiliser la procédure stockée InsertLog()

### ISSUE THREAD

**Issue by GabrielF-C** [WilliamBlais/Modelisation-TP3#1]
L'utilisation de la procédure dans le site et dans workbench me donne l'erreur suivante :
`Can't update table 'Logs' in stored function/trigger because it is already used by statement which invoked this stored function/trigger.`

Je pense que l'erreur pourrait venir de la situation décrite dans ce [post](https://stackoverflow.com/questions/15300673/mysql-error-cant-update-table-in-stored-function-trigger-because-it-is-already)

> You cannot change a table while the INSERT trigger is firing. The INSERT might do some locking which could result in a deadlock. Also, updating the table from a trigger would then cause the same trigger to fire again in an infinite recursive loop. Both of these reasons are why MySQL prevents you from doing this.

**Comment by deadmanlex** [comment]
J'lai corrigée
