### ISSUE TITLE
Faille Sécurité dans delete_comment($comment_id) {

### ISSUE THREAD

**Issue by WilliamBlais** [WilliamBlais/Modelisation-TP3#6]
La fonction delete_comment($comment_id) est accessible par tout les utilisateurs grace a picture.php. Donc un utilisateur mal intentionné pourrait poster comment_to_delete de 1 a 100000 et supprimer tout les commentaires.

To do: Verifier que le commentaire nous appartient OU que la photo nous appartient OU que nous sommes admin avant de permettre la suppression.

**Comment by GabrielF-C** [comment]
![Capture1](https://user-images.githubusercontent.com/45073321/58386749-39bc1d00-7fd2-11e9-9a82-5885cdc29761.PNG)

Devrait faire l'affaire
